/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DemoAvroTypesXxx extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1780929339327780851L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DemoAvroTypesXxx\",\"namespace\":\"com.example.avro\",\"fields\":[{\"name\":\"field1\",\"type\":\"boolean\"},{\"name\":\"field2\",\"type\":\"int\"},{\"name\":\"field3\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DemoAvroTypesXxx> ENCODER =
      new BinaryMessageEncoder<DemoAvroTypesXxx>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DemoAvroTypesXxx> DECODER =
      new BinaryMessageDecoder<DemoAvroTypesXxx>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DemoAvroTypesXxx> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DemoAvroTypesXxx> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DemoAvroTypesXxx> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DemoAvroTypesXxx>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DemoAvroTypesXxx to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DemoAvroTypesXxx from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DemoAvroTypesXxx instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DemoAvroTypesXxx fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private boolean field1;
   private int field2;
   private java.lang.CharSequence field3;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DemoAvroTypesXxx() {}

  /**
   * All-args constructor.
   * @param field1 The new value for field1
   * @param field2 The new value for field2
   * @param field3 The new value for field3
   */
  public DemoAvroTypesXxx(java.lang.Boolean field1, java.lang.Integer field2, java.lang.CharSequence field3) {
    this.field1 = field1;
    this.field2 = field2;
    this.field3 = field3;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return field1;
    case 1: return field2;
    case 2: return field3;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: field1 = (java.lang.Boolean)value$; break;
    case 1: field2 = (java.lang.Integer)value$; break;
    case 2: field3 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'field1' field.
   * @return The value of the 'field1' field.
   */
  public boolean getField1() {
    return field1;
  }


  /**
   * Sets the value of the 'field1' field.
   * @param value the value to set.
   */
  public void setField1(boolean value) {
    this.field1 = value;
  }

  /**
   * Gets the value of the 'field2' field.
   * @return The value of the 'field2' field.
   */
  public int getField2() {
    return field2;
  }


  /**
   * Sets the value of the 'field2' field.
   * @param value the value to set.
   */
  public void setField2(int value) {
    this.field2 = value;
  }

  /**
   * Gets the value of the 'field3' field.
   * @return The value of the 'field3' field.
   */
  public java.lang.CharSequence getField3() {
    return field3;
  }


  /**
   * Sets the value of the 'field3' field.
   * @param value the value to set.
   */
  public void setField3(java.lang.CharSequence value) {
    this.field3 = value;
  }

  /**
   * Creates a new DemoAvroTypesXxx RecordBuilder.
   * @return A new DemoAvroTypesXxx RecordBuilder
   */
  public static com.example.avro.DemoAvroTypesXxx.Builder newBuilder() {
    return new com.example.avro.DemoAvroTypesXxx.Builder();
  }

  /**
   * Creates a new DemoAvroTypesXxx RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DemoAvroTypesXxx RecordBuilder
   */
  public static com.example.avro.DemoAvroTypesXxx.Builder newBuilder(com.example.avro.DemoAvroTypesXxx.Builder other) {
    if (other == null) {
      return new com.example.avro.DemoAvroTypesXxx.Builder();
    } else {
      return new com.example.avro.DemoAvroTypesXxx.Builder(other);
    }
  }

  /**
   * Creates a new DemoAvroTypesXxx RecordBuilder by copying an existing DemoAvroTypesXxx instance.
   * @param other The existing instance to copy.
   * @return A new DemoAvroTypesXxx RecordBuilder
   */
  public static com.example.avro.DemoAvroTypesXxx.Builder newBuilder(com.example.avro.DemoAvroTypesXxx other) {
    if (other == null) {
      return new com.example.avro.DemoAvroTypesXxx.Builder();
    } else {
      return new com.example.avro.DemoAvroTypesXxx.Builder(other);
    }
  }

  /**
   * RecordBuilder for DemoAvroTypesXxx instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DemoAvroTypesXxx>
    implements org.apache.avro.data.RecordBuilder<DemoAvroTypesXxx> {

    private boolean field1;
    private int field2;
    private java.lang.CharSequence field3;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.avro.DemoAvroTypesXxx.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.field1)) {
        this.field1 = data().deepCopy(fields()[0].schema(), other.field1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.field2)) {
        this.field2 = data().deepCopy(fields()[1].schema(), other.field2);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.field3)) {
        this.field3 = data().deepCopy(fields()[2].schema(), other.field3);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing DemoAvroTypesXxx instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.avro.DemoAvroTypesXxx other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.field1)) {
        this.field1 = data().deepCopy(fields()[0].schema(), other.field1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.field2)) {
        this.field2 = data().deepCopy(fields()[1].schema(), other.field2);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.field3)) {
        this.field3 = data().deepCopy(fields()[2].schema(), other.field3);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'field1' field.
      * @return The value.
      */
    public boolean getField1() {
      return field1;
    }


    /**
      * Sets the value of the 'field1' field.
      * @param value The value of 'field1'.
      * @return This builder.
      */
    public com.example.avro.DemoAvroTypesXxx.Builder setField1(boolean value) {
      validate(fields()[0], value);
      this.field1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'field1' field has been set.
      * @return True if the 'field1' field has been set, false otherwise.
      */
    public boolean hasField1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'field1' field.
      * @return This builder.
      */
    public com.example.avro.DemoAvroTypesXxx.Builder clearField1() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'field2' field.
      * @return The value.
      */
    public int getField2() {
      return field2;
    }


    /**
      * Sets the value of the 'field2' field.
      * @param value The value of 'field2'.
      * @return This builder.
      */
    public com.example.avro.DemoAvroTypesXxx.Builder setField2(int value) {
      validate(fields()[1], value);
      this.field2 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'field2' field has been set.
      * @return True if the 'field2' field has been set, false otherwise.
      */
    public boolean hasField2() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'field2' field.
      * @return This builder.
      */
    public com.example.avro.DemoAvroTypesXxx.Builder clearField2() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'field3' field.
      * @return The value.
      */
    public java.lang.CharSequence getField3() {
      return field3;
    }


    /**
      * Sets the value of the 'field3' field.
      * @param value The value of 'field3'.
      * @return This builder.
      */
    public com.example.avro.DemoAvroTypesXxx.Builder setField3(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.field3 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'field3' field has been set.
      * @return True if the 'field3' field has been set, false otherwise.
      */
    public boolean hasField3() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'field3' field.
      * @return This builder.
      */
    public com.example.avro.DemoAvroTypesXxx.Builder clearField3() {
      field3 = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DemoAvroTypesXxx build() {
      try {
        DemoAvroTypesXxx record = new DemoAvroTypesXxx();
        record.field1 = fieldSetFlags()[0] ? this.field1 : (java.lang.Boolean) defaultValue(fields()[0]);
        record.field2 = fieldSetFlags()[1] ? this.field2 : (java.lang.Integer) defaultValue(fields()[1]);
        record.field3 = fieldSetFlags()[2] ? this.field3 : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DemoAvroTypesXxx>
    WRITER$ = (org.apache.avro.io.DatumWriter<DemoAvroTypesXxx>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DemoAvroTypesXxx>
    READER$ = (org.apache.avro.io.DatumReader<DemoAvroTypesXxx>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeBoolean(this.field1);

    out.writeInt(this.field2);

    out.writeString(this.field3);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.field1 = in.readBoolean();

      this.field2 = in.readInt();

      this.field3 = in.readString(this.field3 instanceof Utf8 ? (Utf8)this.field3 : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.field1 = in.readBoolean();
          break;

        case 1:
          this.field2 = in.readInt();
          break;

        case 2:
          this.field3 = in.readString(this.field3 instanceof Utf8 ? (Utf8)this.field3 : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










